import type { Categoria, Produto, Fornecedor, Cliente, MetricasDashboard, Venda, Promocao } from '../types';

// ------ Categorias ------
export const categoriasMock: Categoria[] = [
    { id: '1', nome: 'Frutas', descricao: 'Frutas frescas', cor: '#ff6b6b', icone: '🍎', ativo: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: '2', nome: 'Verduras', descricao: 'Folhagens e legumes', cor: '#51cf66', icone: '🥬', ativo: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
    { id: '3', nome: 'Tubérculos', descricao: 'Batata, cenoura, beterraba', cor: '#ffa94d', icone: '🥕', ativo: true, created_at: new Date().toISOString(), updated_at: new Date().toISOString() },
];

// ------ Fornecedores ------
export const fornecedoresMock: Fornecedor[] = [
    {
        id: '1',
        razao_social: 'Produtor Rural Silva',
        nome_fantasia: 'Silva Frutas',
        telefone: '(11) 99999-0001',
        email: 'silva@email.com',
        tipo: 'produtor_rural',
        ativo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '2',
        razao_social: 'Distribuidor Hortifruti LTDA',
        nome_fantasia: 'Distribuidor Hortifruti',
        cnpj_cpf: '12.345.678/0001-90',
        telefone: '(11) 3333-4444',
        email: 'contato@distribuidor.com.br',
        tipo: 'juridica',
        ativo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

// ------ Produtos ------
export const produtosMock: Produto[] = [
    {
        id: '1',
        nome: 'Maçã Fuji',
        codigo: 'MACA001',
        codigo_barras: '7894567890123',
        categoria_id: '1',
        fornecedor_id: '1',
        unidade: 'KG',
        preco_custo: 2.50,
        preco_venda: 5.99,
        margem_lucro: 139.6,
        estoque_atual: 45,
        estoque_minimo: 10,
        data_validade: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        lote: 'L2026001',
        localizacao: 'A1',
        icms_aliquota: 7,
        pis_aliquota: 1.65,
        cofins_aliquota: 7.6,
        em_promocao: false,
        ativo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        categoria: categoriasMock[0],
        fornecedor: fornecedoresMock[0],
    },
    {
        id: '2',
        nome: 'Alface Crespa',
        codigo: 'ALFA001',
        codigo_barras: '7894567890124',
        categoria_id: '2',
        fornecedor_id: '2',
        unidade: 'UN',
        preco_custo: 1.00,
        preco_venda: 2.99,
        margem_lucro: 199,
        estoque_atual: 120,
        estoque_minimo: 20,
        data_validade: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        lote: 'L2026002',
        localizacao: 'B2',
        icms_aliquota: 0,
        pis_aliquota: 0,
        cofins_aliquota: 0,
        em_promocao: true,
        preco_promocional: 2.49,
        promocao_inicio: new Date().toISOString().split('T')[0],
        promocao_fim: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        ativo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        categoria: categoriasMock[1],
        fornecedor: fornecedoresMock[1],
    },
    {
        id: '3',
        nome: 'Cenoura',
        codigo: 'CENO001',
        codigo_barras: '7894567890125',
        categoria_id: '3',
        fornecedor_id: '1',
        unidade: 'KG',
        preco_custo: 1.50,
        preco_venda: 3.99,
        margem_lucro: 166,
        estoque_atual: 80,
        estoque_minimo: 15,
        data_validade: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        lote: 'L2026003',
        localizacao: 'C1',
        icms_aliquota: 7,
        pis_aliquota: 1.65,
        cofins_aliquota: 7.6,
        em_promocao: false,
        ativo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        categoria: categoriasMock[2],
        fornecedor: fornecedoresMock[0],
    },
    {
        id: '4',
        nome: 'Tomate Caqui',
        codigo: 'TOMA001',
        codigo_barras: '7894567890126',
        categoria_id: '2',
        fornecedor_id: '2',
        unidade: 'KG',
        preco_custo: 2.00,
        preco_venda: 4.99,
        margem_lucro: 149.5,
        estoque_atual: 5,
        estoque_minimo: 10,
        data_validade: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        lote: 'L2026004',
        localizacao: 'B3',
        icms_aliquota: 7,
        pis_aliquota: 1.65,
        cofins_aliquota: 7.6,
        em_promocao: false,
        ativo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        categoria: categoriasMock[1],
        fornecedor: fornecedoresMock[1],
    },
    {
        id: '5',
        nome: 'Banana Prata',
        codigo: 'BANA001',
        codigo_barras: '7894567890127',
        categoria_id: '1',
        fornecedor_id: '1',
        unidade: 'KG',
        preco_custo: 1.80,
        preco_venda: 3.49,
        margem_lucro: 93.9,
        estoque_atual: 8,
        estoque_minimo: 15,
        data_validade: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        lote: 'L2026005',
        localizacao: 'A2',
        icms_aliquota: 7,
        pis_aliquota: 1.65,
        cofins_aliquota: 7.6,
        em_promocao: false,
        ativo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
        categoria: categoriasMock[0],
        fornecedor: fornecedoresMock[0],
    },
];

// ------ Clientes ------
export const clientesMock: Cliente[] = [
    {
        id: '1',
        nome: 'João Silva',
        cpf_cnpj: '123.456.789-00',
        telefone: '(11) 98765-4321',
        email: 'joao@email.com',
        endereco: 'Rua A, 123',
        cidade: 'São Paulo',
        estado: 'SP',
        cep: '01234-567',
        limite_credito: 500.00,
        saldo_credito: 250.00,
        pontos_fidelidade: 150,
        ativo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '2',
        nome: 'Maria Santos',
        cpf_cnpj: '987.654.321-00',
        telefone: '(11) 91234-5678',
        email: 'maria@email.com',
        endereco: 'Av. B, 456',
        cidade: 'São Paulo',
        estado: 'SP',
        cep: '02345-678',
        limite_credito: 1000.00,
        saldo_credito: 0.00,
        pontos_fidelidade: 500,
        ativo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '3',
        nome: 'Pedro Oliveira',
        cpf_cnpj: '111.222.333-44',
        telefone: '(11) 97777-8888',
        email: 'pedro@email.com',
        endereco: 'Rua C, 789',
        cidade: 'São Paulo',
        estado: 'SP',
        cep: '03456-789',
        limite_credito: 800.00,
        saldo_credito: 100.00,
        pontos_fidelidade: 2100,
        ativo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

// ------ Promoções ------
export const promocoesMock: Promocao[] = [
    {
        id: '1',
        nome: '10% Off em Frutas',
        descricao: 'Desconto especial em todas as frutas desta semana',
        tipo: 'percentual',
        valor_desconto: 10,
        quantidade_minima: 1,
        data_inicio: new Date().toISOString().split('T')[0],
        data_fim: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        ativo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: '2',
        nome: 'Leve 3 Pague 2 — Verduras',
        descricao: 'Na compra de 3 unidades de verduras, pague apenas 2',
        tipo: 'quantidade',
        quantidade_minima: 3,
        data_inicio: new Date().toISOString().split('T')[0],
        data_fim: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
        ativo: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
];

// ------ Métricas do Dashboard ------
// Atenção: os tipos aqui DEVEM coincidir com MetricasDashboard em types/index.ts
export const metricasMock: MetricasDashboard = {
    vendasHoje: 1250.50,
    ticketMedio: 125.05,
    produtosVendidos: 45,
    alertasAtivos: 3,
    vendasSemana: [
        { dia: 'Seg', valor: 850 },
        { dia: 'Ter', valor: 1050 },
        { dia: 'Qua', valor: 1200 },
        { dia: 'Qui', valor: 950 },
        { dia: 'Sex', valor: 1400 },
        { dia: 'Sáb', valor: 1600 },
        { dia: 'Dom', valor: 700 },
    ],
    vendasPorCategoria: [
        { nome: 'Frutas', valor: 3500, cor: '#ff6b6b' },
        { nome: 'Verduras', valor: 2800, cor: '#51cf66' },
        { nome: 'Tubérculos', valor: 1250, cor: '#ffa94d' },
    ],
    topProdutos: [
        { nome: 'Alface Crespa', quantidade: 150, valor: 450 },
        { nome: 'Maçã Fuji', quantidade: 85, valor: 509 },
        { nome: 'Cenoura', quantidade: 120, valor: 479 },
        { nome: 'Tomate Caqui', quantidade: 60, valor: 299 },
        { nome: 'Banana Prata', quantidade: 95, valor: 332 },
    ],
    ultimasVendas: [] as Venda[],
    alertasEstoque: [
        { produto: 'Tomate Caqui', tipo: 'ruptura', detalhe: 'Estoque: 5 (mínimo: 10)' },
        { produto: 'Banana Prata', tipo: 'ruptura', detalhe: 'Estoque: 8 (mínimo: 15)' },
        { produto: 'Alface Crespa', tipo: 'vencimento', detalhe: 'Vence em 5 dias' },
    ],
};
