-- =============================================
-- Desabilitar RLS temporariamente para teste
-- =============================================

-- Desabilitar RLS em todas as tabelas
ALTER TABLE categorias DISABLE ROW LEVEL SECURITY;
ALTER TABLE fornecedores DISABLE ROW LEVEL SECURITY;
ALTER TABLE produtos DISABLE ROW LEVEL SECURITY;
ALTER TABLE clientes DISABLE ROW LEVEL SECURITY;
ALTER TABLE vendas DISABLE ROW LEVEL SECURITY;
ALTER TABLE venda_itens DISABLE ROW LEVEL SECURITY;
ALTER TABLE venda_pagamentos DISABLE ROW LEVEL SECURITY;
ALTER TABLE caixas DISABLE ROW LEVEL SECURITY;
ALTER TABLE movimentacoes_caixa DISABLE ROW LEVEL SECURITY;
ALTER TABLE movimentacoes_estoque DISABLE ROW LEVEL SECURITY;
ALTER TABLE contas_pagar DISABLE ROW LEVEL SECURITY;
ALTER TABLE contas_receber DISABLE ROW LEVEL SECURITY;
ALTER TABLE pedidos_compra DISABLE ROW LEVEL SECURITY;
ALTER TABLE pedido_compra_itens DISABLE ROW LEVEL SECURITY;
ALTER TABLE promocoes DISABLE ROW LEVEL SECURITY;
ALTER TABLE promocao_produtos DISABLE ROW LEVEL SECURITY;
ALTER TABLE registros_qualidade DISABLE ROW LEVEL SECURITY;
ALTER TABLE perdas DISABLE ROW LEVEL SECURITY;
ALTER TABLE rastreios DISABLE ROW LEVEL SECURITY;
ALTER TABLE sazonalidade DISABLE ROW LEVEL SECURITY;
